name: Hello World

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
     - name: Run a one-line script
       run: echo Hello, world!
